fragment PageParts on Page {
  blocks {
    __typename
    ... on PageBlocksBanner {
      headline
      text
      cta
      image
    }
    ... on PageBlocksServices {
      title
      description
      features {
        __typename
        image {
          __typename
          img
          alt
        }
        featTitle
        featText
      }
    }
  }
}

fragment GlobalParts on Global {
  header {
    __typename
    color
    nav {
      __typename
      href
      label
    }
  }
  footer {
    __typename
    color
    social {
      __typename
      facebook
      twitter
      instagram
      github
    }
  }
  theme {
    __typename
    color
    font
    icon
    darkMode
  }
}

fragment PostsParts on Posts {
  title
  body
}
